title: Webflix
email: stoyangalchev98@gmail.com
description: This is a description of my awesome site.
baseurl: "/webflix"
url: "https://stoyangalchev.github.io"
twitter_username: jekyllrb
github_username:  jekyll
markdown:  kramdown
theme: minima
plugins:
  - jekyll-feed